### ISSUE TITLE
Warlord Cliques National Idea value changes

### ISSUE THREAD

**Issue by deliciousmods** [deliciousmods/1956_beta#8] opened 2018-03-15 19:58 UTC
The penalties from Warlord Cliques lower on their own by January 30 1936 with no event telling why.

**Comment by Zurich899** [comment] 2018-05-03 03:57
I can't reproduce this issue after loading one of the warlords and let the game run until May. None of their penalty ideas lowered in the time that the game was running, and I think we can close this issue.
![warlord1](https://user-images.githubusercontent.com/13583641/39559472-a91ceace-4ec0-11e8-8b1c-f4a620d93b67.png)
![warlord2](https://user-images.githubusercontent.com/13583641/39559474-a952ad44-4ec0-11e8-9af8-0cbd1234939f.png)

**Comment by Greatexperiment** [comment] 2018-06-05 21:39
Thanks.

**Closed by Greatexperiment** 2018-06-05 21:39 UTC
Labels: bug, confirmed, minor
